name: Daily Java Job Alert

on:
  schedule:
    # 03:00 UTC = 08:30 AM IST
    - cron: '0 3 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub UI anytime

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Script & Send Digest
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python crawler.py